spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cookmaster_dev
    username: cookmaster_dev_user
    password: dev
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true
    #Now to create the schema for mysql ,we'll use hibernate to generate it for us
    #So we create a source of metadata which will basically do a reflection  upon
    #our entities
#    properties:
#      javax:
#        persistence:
#          schema-generation:
#            create-source: metadata
#            scripts:
#              action: create
#              create-target: generated_scehma.sql # will output to the project's root folder