spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cookmaster_prod
    username: cookmaster_prod_user
    # a good practice is to send the password as an environment variable , not like this
    password: prod
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: false
