version: 2
workflows:
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk-node
    working_directory: ~/repo
    environment:
      # Customize the VM max heap limit
      MVN_OPTS: -Xm3200m
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{checksum "pom.xml"}}
            - v1-dependencies-

      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{checksum "pom.xml"}}
      #changed from [- run: mvn integration-test] for circleci build issues
      - run: mvn integration-test
      #!!!because CodeCov.io doesn't support jdk 11
      #- store_test_results:
          #path: target/surfire-reports
      #- run:
          #name: Send To CodeCov
          #command: bash <(curl -s https://codecov.io/bash)